<?
$PERM["about"]["8"]="W";
$PERM["close"]["2"]="D";
$PERM["pub"]["9"]="T_8";
$PERM["pub"]["5"]="T_8";
$PERM["upload"]["9"]="T_8";
$PERM["upload"]["5"]="T_8";
$PERM["online"]["*"]="R";
$PERM["desktop_app"]["*"]="R";
$PERM["personal"]["8"]="W";
$PERM["catalog"]["8"]="W";
$PERM["news"]["8"]="W";
$PERM["index.php"]["8"]="W";
$PERM["/"]["*"]="R";
?>